### ISSUE TITLE
 rates and direct encoding

### ISSUE THREAD

**Issue by liyanjie001** [Intelligent-Computing-Lab-Yale/Rate-vs-Direct#1]
I have some questions about rates and direct encoding that I would like to ask you. In this paper, _RATE CODING OR DIRECT CODING: WHICH ONE IS BETTER FOR ACCURATE, ROBUST, AND ENERGY-EFFICIENT SPIKING NEURAL NETWORKS?_you set the threshold voltage of each layer to 1 in both VGG5 and VGG9 networks. Can this value be decreased or increased?

**Comment by liyanjie001** [comment]
hello,I have some questions about rates and direct encoding that I would like to ask you. In this paper, _RATE CODING OR DIRECTCODING: WHICH ONE IS BETTER FOR ACCURATE, ROBUST, AND ENERGY-EFFICIENT SPIKING NEURAL NETWORKS?_you set the threshold voltage of each layer to 1 in both VGG5 and VGG9 networks. Can this value be decreased or increased?

**Comment by youngryan1993** [comment]
Hi thanks for the question.

Sure, you can change the threshold value in the code "m.threshold = 1.0". Based on my experience, too large or too small threshold value decreases the accuracy.

**Comment by lotusroot-kim** [comment]
Hi thanks for the question.

Sure, you can change the threshold value in the code "m.threshold = 1.0". Based on my experience, too large or too small threshold value decreases the accuracy.
